# Generated by Django 3.1.1 on 2020-10-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20201030_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
