# Generated by Django 3.1.1 on 2020-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20201030_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
